version: '3.5'
services:
  bot:
    image: registry.kkxo.ru/izumi
    build:
      context: .
      dockerfile: ./Izumi/Dockerfile

  dashboard:
    image: registry.kkxo.ru/izumi-dashboard
    build:
      context: .
      dockerfile: Izumi.Dashboard/Dockerfile
