namespace Izumi.Data.Enums
{
    public enum AchievementType : byte
    {
        FirstMessage = 1,
        FirstTransit = 2,
        FirstFish = 3,
        FirstGatheringResource = 4,
        FirstPlant = 5,
        FirstCraftResource = 6,
        FirstCraftAlcohol = 7,
        FirstCraftDrink = 8,
        FirstCook = 9,
        FirstBet = 10,
        FirstJackPot = 11,
        FirstLotteryTicket = 12,
        FirstMarketDeal = 13,
        FirstContract = 14,
        Gather40Resources = 15,
        Gather250Resources = 16,
        Catch50Fish = 17,
        Catch300Fish = 18,
        CatchEpicFish = 19,
        CatchMythicalFish = 20,
        CatchLegendaryFish = 21,
        Plant25Seed = 22,
        Plant150Seed = 23,
        Collect50Crop = 24,
        Collect300Crop = 25,
        Cook20Food = 26,
        Cook130Food = 27,
        Craft30Resource = 28,
        Craft250Resource = 29,
        Craft10Alcohol = 30,
        Craft80Alcohol = 31,
        Casino33Bet = 32,
        Casino777Bet = 33,
        Casino22LotteryBuy = 34,
        Casino99LotteryBuy = 35,
        Casino20LotteryGift = 36,
        Market100Sell = 37,
        Market666Sell = 38,
        Market50Buy = 39,
        Market333Buy = 40,
        CompleteCollectionGathering = 41,
        CompleteCollectionCrafting = 42,
        CompleteCollectionAlcohol = 43,
        CompleteCollectionCrop = 44,
        CompleteCollectionFish = 45,
        CompleteCollectionFood = 46,
        CompleteCollectionDrink = 47
    }
}
